scope: postgres
namespace: /pg_cluster/
name: pg_node1
restapi:
  listen: 192.168.0.165:8008
  connect_address: 192.168.0.165:8008
etcd:
  hosts: 192.168.0.174:2379,192.168.0.165:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        max_connections: 20
        max_worker_processes: 8
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        max_prepared_transactions: 0
        max_locks_per_transaction: 64
        wal_log_hints: "on"
        track_commit_timestamp: "off"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
        synchronous_commit: "on"
        synchronous_standby_names: "*"
      recovery_conf:
        restore_command: cp ../wal_archive/%f %p
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host replication repuser 127.0.0.1/32 md5
  - host replication repuser 192.168.0.0/16 md5
  - host db_1 repuser 127.0.0.1/32 md5
  - host db_1 repuser 192.168.0.0/16 md5
  - host all all 192.168.0.0/16 md5
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: 192.168.0.165:5432
  connect_address: 192.168.0.165:5432
  data_dir: /var/lib/pgsql/16/cluster1
  bin_dir: /usr/bin
  pgpass: /etc/pgpass
  authentication:
    replication:
      username: repuser
      password: repuser
    superuser:
      username: postgres
      password: postgres
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false